context:
  name: supervisor-pydantic
  version: "1.4.3"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/s/supervisor-pydantic/supervisor_pydantic-${{ version }}.tar.gz
  sha256: 26cbeade4ca5b4995d0167d0879760b4e1359064c1f85ad054b2b30a068452d6

build:
  number: 0
  noarch: python
  script: python -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - hatchling
  run:
    - python >=${{ python_min }}
    - colorlog
    - hydra-core
    - jinja2
    - omegaconf
    - pydantic >=2
    - rich
    - typer

tests:
  - python:
      imports:
        - supervisor_pydantic
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  license: Apache-2.0
  license_file: LICENSE
  summary: Pydantic models for supervisor
  homepage: https://github.com/airflow-laminar/supervisor-pydantic
  repository: https://github.com/airflow-laminar/supervisor-pydantic

extra:
  recipe-maintainers:
    - timkpaine
